export const siteUrl = 'https://useslovo.ru';

export const languageNames = {
  ru: 'Русский', en: 'English', es: 'Español', de: 'Deutsch', fr: 'Français',
  it: 'Italiano', pt: 'Português', zh: '中文', ja: '日本語', ko: '한국어',
  tr: 'Türkçe', uk: 'Українська',
};

export const locales = {
  ru: {
    locale: 'ru_RU', title: 'Слово — бесплатный переводчик для macOS',
    description: 'Быстрый и приватный переводчик для macOS. Переводите выделенный текст горячей клавишей, онлайн или прямо на устройстве.',
    skip: 'Перейти к содержанию', home: 'Слово — на главную', openMenu: 'Открыть меню', chooseLanguage: 'Выбрать язык',
    nav: ['Возможности', 'Приватность', 'Как работает', 'Скачать'], eyebrow: 'Переводчик для macOS',
    hero: ['Мысль остаётся.', 'Язык меняется.', 'Переводите выделенный текст, не выпадая из контекста. Одно сочетание клавиш — и точный перевод уже рядом.', 'Скачать для Mac', 'Посмотреть, как работает', 'Бесплатно · macOS 15 и новее · Открытый исходный код'],
    app: ['Переводчик для macOS', 'На устройстве', 'Авто', 'Русский', 'Перевести', 'Выделить и перевести', 'Горячая клавиша', 'Готово', 'Hello! How are you doing today?', 'Привет! Как у тебя сегодня дела?'],
    stats: [['12', 'языков'], ['1', 'горячая клавиша'], ['0 ₽', 'навсегда'], ['100%', 'контроль приватности']],
    featuresHead: ['Всё нужное рядом', 'Перевод без лишних движений', 'Слово живёт в строке меню и появляется только тогда, когда нужно.'],
    features: [['Выделили. Нажали. Поняли.', 'Переводите текст прямо из браузера, документа или чата. Не нужно копировать, открывать вкладку и вставлять.'], ['Онлайн или офлайн', 'Google Translate для повседневных задач или Apple Translation — полностью на устройстве.'], ['История под рукой', 'Последние переводы сохраняются локально — удобно вернуться к нужной фразе.']],
    demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', 'Самый маленький добрый поступок ценнее самого грандиозного намерения.'],
    engine: ['На устройстве', 'Apple Translation', 'Онлайн', 'Google Translate'], history: [['Hello', 'Привет', 'сейчас'], ['Thank you', 'Спасибо', '2 мин'], ['See you soon', 'До скорого', '8 мин']],
    privacy: ['Приватность по умолчанию', 'Ваши слова —', 'только ваши', 'Включите режим «Только офлайн», и текст не покинет ваш Mac. Индикатор всегда показывает, где выполнен перевод.', 'Никакой регистрации', 'История хранится локально', 'Открытый исходный код', 'Только на Mac', 'Вы решаете', 'Без аккаунта'],
    how: ['Три простых шага', 'Работает с первой минуты'], steps: [['Установите', 'Перенесите Слово в папку «Программы».'], ['Выделите текст', 'В любом приложении на вашем Mac.'], ['Получите перевод', 'Он появится в компактном окне рядом.']],
    cta: ['Пусть язык больше', 'не останавливает', 'Скачайте Слово и переводите то, что действительно важно.', 'Скачать Слово {version}', 'GitHub Release · macOS 15+'],
    github: ['Открытый исходный код', 'Весь проект — на GitHub', 'Исходный код Слова полностью открыт. Изучайте устройство приложения, собирайте его самостоятельно, сообщайте об ошибках и предлагайте улучшения.', 'Открыть репозиторий', 'Посмотреть релиз {version}', 'MIT License · Swift 6 · GitHub Actions'],
    tagline: 'Переводите мысли, не отвлекаясь от них.', privacyLink: 'Приватность', toast: 'Ссылка на релиз появится после публикации',
  },
  en: {
    locale: 'en_US', title: 'Slovo — free translator for macOS',
    description: 'A fast, private translator for macOS. Translate selected text with a keyboard shortcut, online or entirely on your device.',
    skip: 'Skip to content', home: 'Slovo — home', openMenu: 'Open menu', chooseLanguage: 'Choose language',
    nav: ['Features', 'Privacy', 'How it works', 'Download'], eyebrow: 'Translator for macOS',
    hero: ['Keep the thought.', 'Change the language.', 'Translate selected text without losing your flow. One keyboard shortcut — and an accurate translation appears right beside you.', 'Download for Mac', 'See how it works', 'Free · macOS 15 or later · Open source'],
    app: ['Translator for macOS', 'On device', 'Auto', 'English', 'Translate', 'Select and translate', 'Keyboard shortcut', 'Ready', 'Привет! Как у тебя сегодня дела?', 'Hello! How are you doing today?'],
    stats: [['12', 'languages'], ['1', 'keyboard shortcut'], ['$0', 'forever'], ['100%', 'privacy control']],
    featuresHead: ['Everything close at hand', 'Translation without the extra steps', 'Slovo lives in your menu bar and appears only when you need it.'],
    features: [['Select. Press. Understand.', 'Translate text right from a browser, document, or chat. No copying, opening another tab, and pasting.'], ['Online or offline', 'Google Translate for everyday tasks or Apple Translation — entirely on your device.'], ['History at hand', 'Recent translations are stored locally, so the phrase you need is easy to find again.']],
    demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', 'Самый маленький добрый поступок ценнее самого грандиозного намерения.'],
    engine: ['On device', 'Apple Translation', 'Online', 'Google Translate'], history: [['Hello', 'Привет', 'now'], ['Thank you', 'Спасибо', '2 min'], ['See you soon', 'До скорого', '8 min']],
    privacy: ['Private by default', 'Your words are', 'yours alone', 'Turn on Offline Only and your text never leaves your Mac. The indicator always shows where translation happens.', 'No registration', 'History stays local', 'Open source', 'Only on Mac', 'You decide', 'No account'],
    how: ['Three simple steps', 'Works from the first minute'], steps: [['Install', 'Move Slovo to your Applications folder.'], ['Select text', 'In any app on your Mac.'], ['Get the translation', 'It appears in a compact window nearby.']],
    cta: ['Let language', 'stop holding you back', 'Download Slovo and translate what truly matters.', 'Download Slovo {version}', 'GitHub Release · macOS 15+'],
    github: ['Open source', 'The whole project is on GitHub', 'Slovo’s source code is completely open. Explore how it works, build it yourself, report issues, or suggest improvements.', 'Open repository', 'View release {version}', 'MIT License · Swift 6 · GitHub Actions'],
    tagline: 'Translate ideas without losing your flow.', privacyLink: 'Privacy', toast: 'The release link will appear after publication',
  },
  es: {
    locale: 'es_ES', title: 'Slovo — traductor gratis para macOS', description: 'Traductor rápido y privado para macOS. Traduce texto seleccionado con un atajo, en línea o directamente en tu dispositivo.',
    skip: 'Ir al contenido', home: 'Slovo — inicio', openMenu: 'Abrir menú', chooseLanguage: 'Elegir idioma', nav: ['Funciones', 'Privacidad', 'Cómo funciona', 'Descargar'], eyebrow: 'Traductor para macOS',
    hero: ['La idea permanece.', 'El idioma cambia.', 'Traduce texto seleccionado sin perder el hilo. Un atajo de teclado y la traducción aparece a tu lado.', 'Descargar para Mac', 'Ver cómo funciona', 'Gratis · macOS 15 o posterior · Código abierto'],
    app: ['Traductor para macOS', 'En el dispositivo', 'Auto', 'Español', 'Traducir', 'Seleccionar y traducir', 'Atajo de teclado', 'Listo', 'Hello! How are you doing today?', '¡Hola! ¿Cómo estás hoy?'],
    stats: [['12', 'idiomas'], ['1', 'atajo de teclado'], ['0 €', 'para siempre'], ['100%', 'control de privacidad']], featuresHead: ['Todo a mano', 'Traduce sin pasos de más', 'Slovo vive en la barra de menús y aparece solo cuando lo necesitas.'],
    features: [['Selecciona. Pulsa. Entiende.', 'Traduce desde el navegador, un documento o un chat. Sin copiar, abrir otra pestaña ni pegar.'], ['En línea o sin conexión', 'Google Translate para el día a día o Apple Translation, totalmente en tu dispositivo.'], ['Historial a mano', 'Las traducciones recientes se guardan localmente para volver a ellas fácilmente.']],
    demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', 'El acto de bondad más pequeño vale más que la intención más grande.'], engine: ['En el dispositivo', 'Apple Translation', 'En línea', 'Google Translate'], history: [['Hello', 'Hola', 'ahora'], ['Thank you', 'Gracias', '2 min'], ['See you soon', 'Hasta pronto', '8 min']],
    privacy: ['Privacidad por defecto', 'Tus palabras son', 'solo tuyas', 'Activa «Solo sin conexión» y el texto nunca saldrá de tu Mac. El indicador siempre muestra dónde se traduce.', 'Sin registro', 'Historial local', 'Código abierto', 'Solo en tu Mac', 'Tú decides', 'Sin cuenta'], how: ['Tres pasos sencillos', 'Funciona desde el primer minuto'], steps: [['Instala', 'Mueve Slovo a la carpeta Aplicaciones.'], ['Selecciona texto', 'En cualquier app de tu Mac.'], ['Obtén la traducción', 'Aparece cerca en una ventana compacta.']], cta: ['Que el idioma', 'no te detenga', 'Descarga Slovo y traduce lo que de verdad importa.', 'Descargar Slovo {version}', 'GitHub Release · macOS 15+'], github: ['Código abierto', 'Todo el proyecto está en GitHub', 'El código fuente de Slovo es completamente abierto. Explora cómo funciona, compílalo, informa de errores o propón mejoras.', 'Abrir repositorio', 'Ver versión {version}', 'Licencia MIT · Swift 6 · GitHub Actions'], tagline: 'Traduce ideas sin perder el hilo.', privacyLink: 'Privacidad', toast: 'El enlace aparecerá después de la publicación',
  },
  de: {
    locale: 'de_DE', title: 'Slovo — kostenloser Übersetzer für macOS', description: 'Schneller, privater Übersetzer für macOS. Markierten Text per Tastenkürzel online oder direkt auf dem Gerät übersetzen.',
    skip: 'Zum Inhalt springen', home: 'Slovo — Startseite', openMenu: 'Menü öffnen', chooseLanguage: 'Sprache wählen', nav: ['Funktionen', 'Datenschutz', 'So funktioniert es', 'Download'], eyebrow: 'Übersetzer für macOS',
    hero: ['Der Gedanke bleibt.', 'Die Sprache wechselt.', 'Übersetze markierten Text, ohne den Fokus zu verlieren. Ein Tastenkürzel — und die Übersetzung ist da.', 'Für Mac laden', 'So funktioniert es', 'Kostenlos · macOS 15 oder neuer · Open Source'], app: ['Übersetzer für macOS', 'Auf dem Gerät', 'Auto', 'Deutsch', 'Übersetzen', 'Markieren und übersetzen', 'Tastenkürzel', 'Bereit', 'Hello! How are you doing today?', 'Hallo! Wie geht es dir heute?'],
    stats: [['12', 'Sprachen'], ['1', 'Tastenkürzel'], ['0 €', 'für immer'], ['100%', 'Datenschutzkontrolle']], featuresHead: ['Alles griffbereit', 'Übersetzen ohne Umwege', 'Slovo lebt in der Menüleiste und erscheint nur, wenn du es brauchst.'], features: [['Markieren. Drücken. Verstehen.', 'Direkt im Browser, Dokument oder Chat übersetzen. Kein Kopieren, kein Tabwechsel, kein Einfügen.'], ['Online oder offline', 'Google Translate für den Alltag oder Apple Translation vollständig auf deinem Gerät.'], ['Verlauf griffbereit', 'Letzte Übersetzungen werden lokal gespeichert und sind schnell wiederzufinden.']], demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', 'Die kleinste gute Tat ist mehr wert als die größte Absicht.'], engine: ['Auf dem Gerät', 'Apple Translation', 'Online', 'Google Translate'], history: [['Hello', 'Hallo', 'jetzt'], ['Thank you', 'Danke', '2 Min.'], ['See you soon', 'Bis bald', '8 Min.']],
    privacy: ['Standardmäßig privat', 'Deine Worte gehören', 'nur dir', 'Mit „Nur offline“ verlässt dein Text den Mac nie. Die Anzeige zeigt stets, wo übersetzt wird.', 'Keine Registrierung', 'Verlauf bleibt lokal', 'Open Source', 'Nur auf dem Mac', 'Du entscheidest', 'Kein Konto'], how: ['Drei einfache Schritte', 'Ab der ersten Minute bereit'], steps: [['Installieren', 'Slovo in den Programme-Ordner verschieben.'], ['Text markieren', 'In jeder App auf deinem Mac.'], ['Übersetzung erhalten', 'Sie erscheint in einem kompakten Fenster.']], cta: ['Lass dich von Sprache', 'nicht mehr aufhalten', 'Lade Slovo und übersetze, was wirklich zählt.', 'Slovo {version} laden', 'GitHub Release · macOS 15+'], github: ['Open Source', 'Das ganze Projekt ist auf GitHub', 'Der Quellcode von Slovo ist vollständig offen. Funktionsweise ansehen, selbst bauen, Fehler melden oder Verbesserungen vorschlagen.', 'Repository öffnen', 'Release {version} ansehen', 'MIT-Lizenz · Swift 6 · GitHub Actions'], tagline: 'Gedanken übersetzen, ohne den Fokus zu verlieren.', privacyLink: 'Datenschutz', toast: 'Der Release-Link erscheint nach der Veröffentlichung',
  },
  fr: {
    locale: 'fr_FR', title: 'Slovo — traducteur gratuit pour macOS', description: 'Un traducteur rapide et privé pour macOS. Traduisez le texte sélectionné avec un raccourci, en ligne ou directement sur votre appareil.',
    skip: 'Aller au contenu', home: 'Slovo — accueil', openMenu: 'Ouvrir le menu', chooseLanguage: 'Choisir la langue', nav: ['Fonctions', 'Confidentialité', 'Fonctionnement', 'Télécharger'], eyebrow: 'Traducteur pour macOS',
    hero: ['La pensée demeure.', 'La langue change.', 'Traduisez le texte sélectionné sans perdre le fil. Un raccourci clavier, et la traduction apparaît à vos côtés.', 'Télécharger pour Mac', 'Voir le fonctionnement', 'Gratuit · macOS 15 ou ultérieur · Open source'], app: ['Traducteur pour macOS', 'Sur l’appareil', 'Auto', 'Français', 'Traduire', 'Sélectionner et traduire', 'Raccourci clavier', 'Prêt', 'Hello! How are you doing today?', 'Bonjour ! Comment allez-vous aujourd’hui ?'],
    stats: [['12', 'langues'], ['1', 'raccourci clavier'], ['0 €', 'pour toujours'], ['100%', 'contrôle de la confidentialité']], featuresHead: ['Tout à portée de main', 'Traduire sans détour', 'Slovo vit dans la barre des menus et n’apparaît que lorsque vous en avez besoin.'], features: [['Sélectionnez. Appuyez. Comprenez.', 'Traduisez depuis un navigateur, un document ou une discussion. Sans copier, changer d’onglet ni coller.'], ['En ligne ou hors ligne', 'Google Translate au quotidien ou Apple Translation entièrement sur votre appareil.'], ['Historique à portée de main', 'Les traductions récentes restent en local pour retrouver facilement une phrase.']], demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', 'Le plus petit acte de bonté vaut mieux que la plus grande intention.'], engine: ['Sur l’appareil', 'Apple Translation', 'En ligne', 'Google Translate'], history: [['Hello', 'Bonjour', 'maintenant'], ['Thank you', 'Merci', '2 min'], ['See you soon', 'À bientôt', '8 min']],
    privacy: ['Privé par défaut', 'Vos mots restent', 'les vôtres', 'Activez « Hors ligne uniquement » : le texte ne quitte jamais votre Mac. L’indicateur montre toujours où se fait la traduction.', 'Aucune inscription', 'Historique conservé en local', 'Open source', 'Seulement sur le Mac', 'Vous décidez', 'Sans compte'], how: ['Trois étapes simples', 'Prêt dès la première minute'], steps: [['Installez', 'Placez Slovo dans le dossier Applications.'], ['Sélectionnez du texte', 'Dans n’importe quelle app de votre Mac.'], ['Obtenez la traduction', 'Elle apparaît dans une fenêtre compacte.']], cta: ['Que la langue', 'ne vous arrête plus', 'Téléchargez Slovo et traduisez ce qui compte vraiment.', 'Télécharger Slovo {version}', 'GitHub Release · macOS 15+'], github: ['Code source ouvert', 'Tout le projet est sur GitHub', 'Le code source de Slovo est entièrement ouvert. Explorez son fonctionnement, compilez-le, signalez un problème ou proposez une amélioration.', 'Ouvrir le dépôt', 'Voir la version {version}', 'Licence MIT · Swift 6 · GitHub Actions'], tagline: 'Traduisez vos idées sans perdre le fil.', privacyLink: 'Confidentialité', toast: 'Le lien apparaîtra après la publication',
  },
  it: {
    locale: 'it_IT', title: 'Slovo — traduttore gratuito per macOS', description: 'Traduttore veloce e privato per macOS. Traduci il testo selezionato con una scorciatoia, online o direttamente sul dispositivo.',
    skip: 'Vai al contenuto', home: 'Slovo — home', openMenu: 'Apri menu', chooseLanguage: 'Scegli lingua', nav: ['Funzioni', 'Privacy', 'Come funziona', 'Scarica'], eyebrow: 'Traduttore per macOS', hero: ['Il pensiero resta.', 'La lingua cambia.', 'Traduci il testo selezionato senza perdere il filo. Una scorciatoia e la traduzione è subito accanto a te.', 'Scarica per Mac', 'Scopri come funziona', 'Gratis · macOS 15 o successivo · Open source'], app: ['Traduttore per macOS', 'Sul dispositivo', 'Auto', 'Italiano', 'Traduci', 'Seleziona e traduci', 'Scorciatoia', 'Pronto', 'Hello! How are you doing today?', 'Ciao! Come stai oggi?'],
    stats: [['12', 'lingue'], ['1', 'scorciatoia'], ['0 €', 'per sempre'], ['100%', 'controllo della privacy']], featuresHead: ['Tutto a portata di mano', 'Traduci senza passaggi inutili', 'Slovo vive nella barra dei menu e appare solo quando serve.'], features: [['Seleziona. Premi. Comprendi.', 'Traduci dal browser, da un documento o da una chat. Senza copiare, aprire schede e incollare.'], ['Online oppure offline', 'Google Translate per ogni giorno o Apple Translation interamente sul dispositivo.'], ['Cronologia a portata di mano', 'Le traduzioni recenti restano in locale, pronte da ritrovare.']], demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', 'Il più piccolo gesto di gentilezza vale più della più grande intenzione.'], engine: ['Sul dispositivo', 'Apple Translation', 'Online', 'Google Translate'], history: [['Hello', 'Ciao', 'ora'], ['Thank you', 'Grazie', '2 min'], ['See you soon', 'A presto', '8 min']], privacy: ['Privacy predefinita', 'Le tue parole sono', 'solo tue', 'Attiva «Solo offline» e il testo non lascerà mai il Mac. L’indicatore mostra sempre dove avviene la traduzione.', 'Nessuna registrazione', 'Cronologia locale', 'Open source', 'Solo sul Mac', 'Decidi tu', 'Senza account'], how: ['Tre semplici passaggi', 'Funziona dal primo minuto'], steps: [['Installa', 'Sposta Slovo nella cartella Applicazioni.'], ['Seleziona il testo', 'In qualsiasi app sul Mac.'], ['Ottieni la traduzione', 'Appare in una finestra compatta.']], cta: ['Non lasciare che la lingua', 'ti fermi', 'Scarica Slovo e traduci ciò che conta davvero.', 'Scarica Slovo {version}', 'GitHub Release · macOS 15+'], github: ['Codice aperto', 'L’intero progetto è su GitHub', 'Il codice sorgente di Slovo è completamente aperto. Esplora come funziona, compilalo, segnala problemi o proponi miglioramenti.', 'Apri repository', 'Vedi versione {version}', 'Licenza MIT · Swift 6 · GitHub Actions'], tagline: 'Traduci le idee senza perdere il filo.', privacyLink: 'Privacy', toast: 'Il link apparirà dopo la pubblicazione',
  },
  pt: {
    locale: 'pt_BR', title: 'Slovo — tradutor gratuito para macOS', description: 'Tradutor rápido e privado para macOS. Traduza texto selecionado com um atalho, online ou diretamente no dispositivo.',
    skip: 'Ir para o conteúdo', home: 'Slovo — início', openMenu: 'Abrir menu', chooseLanguage: 'Escolher idioma', nav: ['Recursos', 'Privacidade', 'Como funciona', 'Baixar'], eyebrow: 'Tradutor para macOS', hero: ['A ideia permanece.', 'O idioma muda.', 'Traduza o texto selecionado sem perder o foco. Um atalho de teclado e a tradução aparece ao seu lado.', 'Baixar para Mac', 'Veja como funciona', 'Grátis · macOS 15 ou posterior · Código aberto'], app: ['Tradutor para macOS', 'No dispositivo', 'Auto', 'Português', 'Traduzir', 'Selecionar e traduzir', 'Atalho de teclado', 'Pronto', 'Hello! How are you doing today?', 'Olá! Como você está hoje?'],
    stats: [['12', 'idiomas'], ['1', 'atalho de teclado'], ['R$ 0', 'para sempre'], ['100%', 'controle de privacidade']], featuresHead: ['Tudo ao seu alcance', 'Tradução sem etapas extras', 'Slovo fica na barra de menus e aparece só quando você precisa.'], features: [['Selecione. Pressione. Entenda.', 'Traduza direto do navegador, documento ou conversa. Sem copiar, abrir outra aba e colar.'], ['Online ou offline', 'Google Translate para o dia a dia ou Apple Translation inteiramente no dispositivo.'], ['Histórico à mão', 'As traduções recentes ficam salvas localmente para você reencontrá-las.']], demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', 'O menor ato de bondade vale mais que a maior intenção.'], engine: ['No dispositivo', 'Apple Translation', 'Online', 'Google Translate'], history: [['Hello', 'Olá', 'agora'], ['Thank you', 'Obrigado', '2 min'], ['See you soon', 'Até breve', '8 min']], privacy: ['Privado por padrão', 'Suas palavras são', 'só suas', 'Ative “Somente offline” e o texto nunca sairá do Mac. O indicador sempre mostra onde a tradução acontece.', 'Sem cadastro', 'Histórico local', 'Código aberto', 'Só no Mac', 'Você decide', 'Sem conta'], how: ['Três passos simples', 'Funciona desde o primeiro minuto'], steps: [['Instale', 'Mova o Slovo para a pasta Aplicativos.'], ['Selecione o texto', 'Em qualquer app do Mac.'], ['Receba a tradução', 'Ela aparece em uma janela compacta.']], cta: ['Não deixe o idioma', 'parar você', 'Baixe o Slovo e traduza o que realmente importa.', 'Baixar Slovo {version}', 'GitHub Release · macOS 15+'], github: ['Código aberto', 'O projeto inteiro está no GitHub', 'O código-fonte do Slovo é totalmente aberto. Veja como funciona, compile você mesmo, relate problemas ou sugira melhorias.', 'Abrir repositório', 'Ver versão {version}', 'Licença MIT · Swift 6 · GitHub Actions'], tagline: 'Traduza ideias sem perder o foco.', privacyLink: 'Privacidade', toast: 'O link aparecerá após a publicação',
  },
  zh: {
    locale: 'zh_CN', title: 'Slovo — 免费的 macOS 翻译工具', description: '快速、私密的 macOS 翻译工具。用快捷键翻译所选文本，支持在线或完全在设备端运行。',
    skip: '跳到主要内容', home: 'Slovo — 首页', openMenu: '打开菜单', chooseLanguage: '选择语言', nav: ['功能', '隐私', '使用方法', '下载'], eyebrow: 'macOS 翻译工具', hero: ['思想不变。', '语言随心而变。', '翻译所选文本，无需打断思路。按下一个快捷键，准确译文即刻出现在身边。', '下载 Mac 版', '查看使用方法', '免费 · macOS 15 或更高版本 · 开源'], app: ['macOS 翻译工具', '设备端', '自动', '中文', '翻译', '选择并翻译', '键盘快捷键', '就绪', 'Hello! How are you doing today?', '你好！你今天过得怎么样？'],
    stats: [['12', '种语言'], ['1', '个快捷键'], ['¥0', '永久免费'], ['100%', '隐私可控']], featuresHead: ['一切触手可及', '翻译无需多余步骤', 'Slovo 常驻菜单栏，只在你需要时出现。'], features: [['选中。按下。读懂。', '直接在浏览器、文档或聊天中翻译，无需复制、切换标签页和粘贴。'], ['在线或离线', '日常使用 Google Translate，或通过 Apple Translation 完全在设备端翻译。'], ['历史记录随手可查', '最近的翻译保存在本地，需要时可轻松找回。']], demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', '最微小的善举，也胜过最宏大的意图。'], engine: ['设备端', 'Apple Translation', '在线', 'Google Translate'], history: [['Hello', '你好', '刚刚'], ['Thank you', '谢谢', '2 分钟'], ['See you soon', '回头见', '8 分钟']], privacy: ['默认保护隐私', '你的文字', '只属于你', '开启“仅离线”后，文本绝不会离开你的 Mac。指示器会始终显示翻译发生的位置。', '无需注册', '历史记录保存在本地', '开放源代码', '仅在 Mac 上', '由你决定', '无需账户'], how: ['简单三步', '打开即可使用'], steps: [['安装', '将 Slovo 移到“应用程序”文件夹。'], ['选择文本', '可在 Mac 上的任何应用中操作。'], ['获得翻译', '译文会显示在旁边的小窗口中。']], cta: ['别让语言', '阻挡你的脚步', '下载 Slovo，翻译真正重要的内容。', '下载 Slovo {version}', 'GitHub Release · macOS 15+'], github: ['开放源代码', '完整项目位于 GitHub', 'Slovo 的源代码完全开放。你可以了解其工作方式、自行构建、报告问题或提出改进建议。', '打开代码仓库', '查看 {version} 版本', 'MIT 许可证 · Swift 6 · GitHub Actions'], tagline: '翻译想法，不打断思路。', privacyLink: '隐私', toast: '发布后将在此提供下载链接',
  },
  ja: {
    locale: 'ja_JP', title: 'Slovo — macOS向け無料翻訳アプリ', description: 'macOS向けの高速でプライベートな翻訳アプリ。選択したテキストをショートカットで、オンラインまたはデバイス上で翻訳できます。',
    skip: '本文へ移動', home: 'Slovo — ホーム', openMenu: 'メニューを開く', chooseLanguage: '言語を選択', nav: ['機能', 'プライバシー', '使い方', 'ダウンロード'], eyebrow: 'macOS向け翻訳アプリ', hero: ['考えはそのまま。', '言葉だけを変える。', '流れを止めずに選択したテキストを翻訳。ショートカット一つで、正確な訳がすぐそばに。', 'Mac版をダウンロード', '使い方を見る', '無料 · macOS 15以降 · オープンソース'], app: ['macOS向け翻訳アプリ', 'デバイス上', '自動', '日本語', '翻訳', '選択して翻訳', 'キーボードショートカット', '準備完了', 'Hello! How are you doing today?', 'こんにちは！今日は元気ですか？'],
    stats: [['12', '言語'], ['1', 'ショートカット'], ['¥0', 'ずっと無料'], ['100%', 'プライバシー管理']], featuresHead: ['必要なものをすぐそばに', '余計な操作なしで翻訳', 'Slovoはメニューバーに常駐し、必要なときだけ現れます。'], features: [['選択。押す。理解する。', 'ブラウザ、書類、チャットから直接翻訳。コピーやタブ移動、貼り付けは不要です。'], ['オンラインでもオフラインでも', '普段はGoogle Translate、完全なデバイス内翻訳にはApple Translationを利用できます。'], ['履歴もすぐに確認', '最近の翻訳はローカルに保存され、必要なフレーズを簡単に見つけられます。']], demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', 'どんなに小さな親切も、壮大な意図より価値があります。'], engine: ['デバイス上', 'Apple Translation', 'オンライン', 'Google Translate'], history: [['Hello', 'こんにちは', '今'], ['Thank you', 'ありがとう', '2分'], ['See you soon', 'またね', '8分']], privacy: ['最初からプライベート', 'あなたの言葉は', 'あなただけのもの', '「オフラインのみ」を有効にすると、テキストはMacの外へ出ません。翻訳場所は常に表示されます。', '登録不要', '履歴はローカル保存', 'オープンソース', 'Macの中だけ', '選ぶのはあなた', 'アカウント不要'], how: ['かんたん3ステップ', 'すぐに使い始められます'], steps: [['インストール', 'Slovoをアプリケーションフォルダへ移動。'], ['テキストを選択', 'Mac上のどのアプリでも使えます。'], ['翻訳を確認', '近くのコンパクトなウィンドウに表示されます。']], cta: ['言葉の壁に', '止められないために', 'Slovoをダウンロードして、本当に大切なことを翻訳しましょう。', 'Slovo {version}をダウンロード', 'GitHub Release · macOS 15+'], github: ['オープンソース', 'プロジェクト全体をGitHubで公開', 'Slovoのソースコードは完全に公開されています。仕組みを調べ、自分でビルドし、問題や改善案を共有できます。', 'リポジトリを開く', 'バージョン{version}を見る', 'MITライセンス · Swift 6 · GitHub Actions'], tagline: '思考の流れを止めずに翻訳。', privacyLink: 'プライバシー', toast: '公開後にダウンロードリンクが表示されます',
  },
  ko: {
    locale: 'ko_KR', title: 'Slovo — macOS용 무료 번역기', description: 'macOS를 위한 빠르고 개인정보를 보호하는 번역기. 선택한 텍스트를 단축키로 온라인 또는 기기에서 번역하세요.',
    skip: '본문으로 이동', home: 'Slovo — 홈', openMenu: '메뉴 열기', chooseLanguage: '언어 선택', nav: ['기능', '개인정보 보호', '사용 방법', '다운로드'], eyebrow: 'macOS용 번역기', hero: ['생각은 그대로.', '언어만 바뀝니다.', '흐름을 놓치지 않고 선택한 텍스트를 번역하세요. 단축키 하나면 정확한 번역이 바로 나타납니다.', 'Mac용 다운로드', '사용 방법 보기', '무료 · macOS 15 이상 · 오픈 소스'], app: ['macOS용 번역기', '기기에서', '자동', '한국어', '번역', '선택하여 번역', '키보드 단축키', '준비 완료', 'Hello! How are you doing today?', '안녕하세요! 오늘 기분이 어떠세요?'],
    stats: [['12', '개 언어'], ['1', '개 단축키'], ['₩0', '영원히'], ['100%', '개인정보 제어']], featuresHead: ['필요한 모든 것을 가까이', '불필요한 단계 없는 번역', 'Slovo는 메뉴 막대에 있으며 필요할 때만 나타납니다.'], features: [['선택. 누르기. 이해.', '브라우저, 문서 또는 채팅에서 바로 번역하세요. 복사하거나 탭을 열고 붙여넣을 필요가 없습니다.'], ['온라인 또는 오프라인', '일상에서는 Google Translate, 완전한 기기 내 번역은 Apple Translation을 사용합니다.'], ['바로 찾는 기록', '최근 번역은 로컬에 저장되어 필요한 문장을 쉽게 다시 찾을 수 있습니다.']], demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', '가장 작은 친절도 가장 큰 의도보다 가치 있습니다.'], engine: ['기기에서', 'Apple Translation', '온라인', 'Google Translate'], history: [['Hello', '안녕하세요', '지금'], ['Thank you', '감사합니다', '2분'], ['See you soon', '또 만나요', '8분']], privacy: ['기본으로 보호되는 개인정보', '당신의 말은', '오직 당신의 것', '“오프라인 전용”을 켜면 텍스트가 Mac을 떠나지 않습니다. 표시기가 항상 번역 위치를 알려줍니다.', '가입 불필요', '기록은 로컬에 저장', '오픈 소스', 'Mac 안에서만', '직접 선택', '계정 불필요'], how: ['간단한 세 단계', '첫 순간부터 바로 사용'], steps: [['설치', 'Slovo를 응용 프로그램 폴더로 옮기세요.'], ['텍스트 선택', 'Mac의 어떤 앱에서든 가능합니다.'], ['번역 확인', '가까운 작은 창에 나타납니다.']], cta: ['언어가 더 이상', '당신을 막지 않도록', 'Slovo를 다운로드하고 정말 중요한 것을 번역하세요.', 'Slovo {version} 다운로드', 'GitHub Release · macOS 15+'], github: ['오픈 소스', '전체 프로젝트가 GitHub에 있습니다', 'Slovo의 소스 코드는 완전히 공개되어 있습니다. 작동 방식을 살펴보고 직접 빌드하며 문제나 개선 사항을 공유하세요.', '저장소 열기', '버전 {version} 보기', 'MIT 라이선스 · Swift 6 · GitHub Actions'], tagline: '생각의 흐름을 유지하며 번역하세요.', privacyLink: '개인정보 보호', toast: '출시 후 다운로드 링크가 제공됩니다',
  },
  tr: {
    locale: 'tr_TR', title: 'Slovo — macOS için ücretsiz çevirmen', description: 'macOS için hızlı ve gizli çevirmen. Seçili metni kısayolla, çevrimiçi veya tamamen cihazınızda çevirin.',
    skip: 'İçeriğe geç', home: 'Slovo — ana sayfa', openMenu: 'Menüyü aç', chooseLanguage: 'Dil seç', nav: ['Özellikler', 'Gizlilik', 'Nasıl çalışır', 'İndir'], eyebrow: 'macOS için çevirmen', hero: ['Düşünce kalır.', 'Dil değişir.', 'Akışınızı bozmadan seçili metni çevirin. Tek bir klavye kısayolu ile doğru çeviri hemen yanınızda.', 'Mac için indir', 'Nasıl çalıştığını görün', 'Ücretsiz · macOS 15 veya üzeri · Açık kaynak'], app: ['macOS için çevirmen', 'Cihazda', 'Otomatik', 'Türkçe', 'Çevir', 'Seç ve çevir', 'Klavye kısayolu', 'Hazır', 'Hello! How are you doing today?', 'Merhaba! Bugün nasılsın?'],
    stats: [['12', 'dil'], ['1', 'klavye kısayolu'], ['₺0', 'sonsuza dek'], ['%100', 'gizlilik kontrolü']], featuresHead: ['Her şey elinizin altında', 'Fazladan adım olmadan çeviri', 'Slovo menü çubuğunda yaşar ve yalnızca gerektiğinde görünür.'], features: [['Seç. Bas. Anla.', 'Tarayıcıdan, belgeden veya sohbetten doğrudan çevirin. Kopyalama, sekme açma ve yapıştırma yok.'], ['Çevrimiçi veya çevrimdışı', 'Günlük işler için Google Translate ya da tamamen cihazda Apple Translation.'], ['Geçmiş elinizin altında', 'Son çeviriler yerel olarak saklanır; ihtiyacınız olan ifadeyi kolayca bulursunuz.']], demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', 'En küçük iyilik, en büyük niyetten daha değerlidir.'], engine: ['Cihazda', 'Apple Translation', 'Çevrimiçi', 'Google Translate'], history: [['Hello', 'Merhaba', 'şimdi'], ['Thank you', 'Teşekkürler', '2 dk'], ['See you soon', 'Yakında görüşürüz', '8 dk']], privacy: ['Varsayılan olarak gizli', 'Sözleriniz', 'yalnızca sizin', '“Yalnızca çevrimdışı” modunu açın; metniniz Mac’inizden çıkmasın. Gösterge çevirinin nerede yapıldığını gösterir.', 'Kayıt yok', 'Geçmiş yerel kalır', 'Açık kaynak', 'Yalnızca Mac’te', 'Siz karar verin', 'Hesap yok'], how: ['Üç basit adım', 'İlk dakikadan çalışır'], steps: [['Yükleyin', 'Slovo’yu Uygulamalar klasörüne taşıyın.'], ['Metni seçin', 'Mac’inizdeki herhangi bir uygulamada.'], ['Çeviriyi alın', 'Yakındaki kompakt bir pencerede görünür.']], cta: ['Dil artık', 'sizi durdurmasın', 'Slovo’yu indirin ve gerçekten önemli olanı çevirin.', 'Slovo {version}’i indir', 'GitHub Release · macOS 15+'], github: ['Açık kaynak', 'Projenin tamamı GitHub’da', 'Slovo’nun kaynak kodu tamamen açıktır. Nasıl çalıştığını inceleyin, kendiniz derleyin, sorun bildirin veya iyileştirme önerin.', 'Depoyu aç', 'Sürüm {version}’i görüntüle', 'MIT Lisansı · Swift 6 · GitHub Actions'], tagline: 'Akışınızı kaybetmeden düşünceleri çevirin.', privacyLink: 'Gizlilik', toast: 'Yayınlandıktan sonra sürüm bağlantısı burada olacak',
  },
  uk: {
    locale: 'uk_UA', title: 'Слово — безкоштовний перекладач для macOS', description: 'Швидкий і приватний перекладач для macOS. Перекладайте виділений текст клавішами, онлайн або просто на пристрої.',
    skip: 'Перейти до вмісту', home: 'Слово — головна', openMenu: 'Відкрити меню', chooseLanguage: 'Вибрати мову', nav: ['Можливості', 'Приватність', 'Як працює', 'Завантажити'], eyebrow: 'Перекладач для macOS', hero: ['Думка залишається.', 'Мова змінюється.', 'Перекладайте виділений текст, не втрачаючи контексту. Одне сполучення клавіш — і точний переклад уже поруч.', 'Завантажити для Mac', 'Подивитися, як працює', 'Безкоштовно · macOS 15 або новіша · Відкритий код'], app: ['Перекладач для macOS', 'На пристрої', 'Авто', 'Українська', 'Перекласти', 'Виділити й перекласти', 'Сполучення клавіш', 'Готово', 'Hello! How are you doing today?', 'Привіт! Як ти сьогодні?'],
    stats: [['12', 'мов'], ['1', 'сполучення клавіш'], ['0 ₴', 'назавжди'], ['100%', 'контроль приватності']], featuresHead: ['Усе потрібне поруч', 'Переклад без зайвих рухів', 'Слово живе в рядку меню й з’являється лише тоді, коли потрібне.'], features: [['Виділили. Натиснули. Зрозуміли.', 'Перекладайте просто з браузера, документа чи чату. Не потрібно копіювати, відкривати вкладку й вставляти.'], ['Онлайн або офлайн', 'Google Translate для щоденних завдань або Apple Translation повністю на пристрої.'], ['Історія під рукою', 'Останні переклади зберігаються локально — потрібну фразу легко знайти знову.']], demoQuote: ['The smallest act of kindness is worth more than the grandest intention.', 'Найменший добрий вчинок цінніший за найбільший намір.'], engine: ['На пристрої', 'Apple Translation', 'Онлайн', 'Google Translate'], history: [['Hello', 'Привіт', 'зараз'], ['Thank you', 'Дякую', '2 хв'], ['See you soon', 'До зустрічі', '8 хв']], privacy: ['Приватність за замовчуванням', 'Ваші слова —', 'лише ваші', 'Увімкніть «Лише офлайн», і текст не залишить ваш Mac. Індикатор завжди показує, де виконується переклад.', 'Жодної реєстрації', 'Історія зберігається локально', 'Відкритий код', 'Лише на Mac', 'Вирішуєте ви', 'Без облікового запису'], how: ['Три прості кроки', 'Працює з першої хвилини'], steps: [['Установіть', 'Перенесіть Слово до папки «Програми».'], ['Виділіть текст', 'У будь-якій програмі на вашому Mac.'], ['Отримайте переклад', 'Він з’явиться в компактному вікні поруч.']], cta: ['Нехай мова більше', 'не зупиняє', 'Завантажте Слово й перекладайте те, що справді важливо.', 'Завантажити Слово {version}', 'GitHub Release · macOS 15+'], github: ['Відкритий код', 'Увесь проєкт — на GitHub', 'Вихідний код Слова повністю відкритий. Досліджуйте роботу застосунку, збирайте його самостійно, повідомляйте про помилки й пропонуйте покращення.', 'Відкрити репозиторій', 'Переглянути реліз {version}', 'MIT License · Swift 6 · GitHub Actions'], tagline: 'Перекладайте думки, не відволікаючись від них.', privacyLink: 'Приватність', toast: 'Посилання на реліз з’явиться після публікації',
  },
};

const withFallback = (code, overrides) => ({ ...locales.en, ...overrides, locale: overrides.locale, title: overrides.title, description: overrides.description });

locales.zh = withFallback('zh', locales.zh);
locales.ja = withFallback('ja', locales.ja);
locales.ko = withFallback('ko', locales.ko);
locales.tr = withFallback('tr', locales.tr);
locales.uk = withFallback('uk', locales.uk);

export const languageCodes = Object.keys(languageNames);
